var struct_d3_d12___r_e_n_d_e_r___p_a_s_s___b_e_g_i_n_n_i_n_g___a_c_c_e_s_s___p_r_e_s_e_r_v_e___l_o_c_a_l___p_a_r_a_m_e_t_e_r_s =
[
    [ "AdditionalHeight", "struct_d3_d12___r_e_n_d_e_r___p_a_s_s___b_e_g_i_n_n_i_n_g___a_c_c_e_s_s___p_r_e_s_e_r_v_e___l_o_c_a_l___p_a_r_a_m_e_t_e_r_s.html#aa2c3ef3ccf6c0878558ad757a65ccafe", null ],
    [ "AdditionalWidth", "struct_d3_d12___r_e_n_d_e_r___p_a_s_s___b_e_g_i_n_n_i_n_g___a_c_c_e_s_s___p_r_e_s_e_r_v_e___l_o_c_a_l___p_a_r_a_m_e_t_e_r_s.html#ae6b523819d9be7f6d63760da9f1ed2b2", null ]
];