var struct_d3_d12___v_i_d_e_o___e_n_c_o_d_e_r___r_e_s_o_l_v_e___m_e_t_a_d_a_t_a___o_u_t_p_u_t___a_r_g_u_m_e_n_t_s =
[
    [ "ResolvedLayoutMetadata", "struct_d3_d12___v_i_d_e_o___e_n_c_o_d_e_r___r_e_s_o_l_v_e___m_e_t_a_d_a_t_a___o_u_t_p_u_t___a_r_g_u_m_e_n_t_s.html#ae2b4036205031e1cb2986fb7fb49b3c9", null ]
];