var struct_d3_d12___r_a_y_t_r_a_c_i_n_g___a_c_c_e_l_e_r_a_t_i_o_n___s_t_r_u_c_t_u_r_e___p_o_s_t_b_u_i_l_d___i_n_f_o___d_e_s_c =
[
    [ "DestBuffer", "struct_d3_d12___r_a_y_t_r_a_c_i_n_g___a_c_c_e_l_e_r_a_t_i_o_n___s_t_r_u_c_t_u_r_e___p_o_s_t_b_u_i_l_d___i_n_f_o___d_e_s_c.html#a7d997b63c714dbf8b5db8e8809ba3dfd", null ],
    [ "InfoType", "struct_d3_d12___r_a_y_t_r_a_c_i_n_g___a_c_c_e_l_e_r_a_t_i_o_n___s_t_r_u_c_t_u_r_e___p_o_s_t_b_u_i_l_d___i_n_f_o___d_e_s_c.html#a6a6b6604ef842d8b1636a202ce1f1dff", null ]
];