var struct_d3_d12___v_i_d_e_o___e_n_c_o_d_e_r___r_a_t_e___c_o_n_t_r_o_l___a_b_s_o_l_u_t_e___q_p___m_a_p =
[
    [ "QualityVsSpeed", "struct_d3_d12___v_i_d_e_o___e_n_c_o_d_e_r___r_a_t_e___c_o_n_t_r_o_l___a_b_s_o_l_u_t_e___q_p___m_a_p.html#ac87638ef6932a22cd310ec5c3b2e0742", null ]
];